name: garden_iot
description: Garden IoT monitoring and watering control app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  syncfusion_flutter_gauges: ^24.0.0
  http: ^1.2.0
  provider: ^6.1.0
  mqtt_client: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/certs/AmazonRootCA1.pem
    - assets/certs/5eb3ad97272b2323f222e6efad963ec376e28fc2ef344f17d5e858a11bffe96f-certificate.pem.crt
    - assets/certs/5eb3ad97272b2323f222e6efad963ec376e28fc2ef344f17d5e858a11bffe96f-private.pem.key
